language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "Wtg/eI9DhJX/3DpOYVIjK1CHIwcHVnep69NzlQxoo0Zfh3eQD+D0vp1Iu0HhzmHDxtXxsSsrjs6xVx5IzOoCrq/UOlLyHcGao9YX7+Psi9STHkyvqOtyJuyjsloR8DzPYtOYCjv8DBtEgSsybxcSGKVJFTXC7gnJff6hM9e8FFdByaf1LVCXHrsoYWPiz6uY4t5BWup8e2RlIdnk8zgnmzC4YalWtrySkHRX8stKeT1qCkMcZWjXDL9l2hZDK/t/KoSKk/GWCP3EOC0XGBZlZPkXKwrV98khqwnK1Uc06jocKMmt4TUN8uLBfNe3hNHp1HcMEr0cXiTyZB3phcyJJTybQeDyu9llmC2hhh780Tqtt15oGWmOIRV1kjEdcK+JkgGw0KN/Z2C7Av/sdfkgn7dQ36/x0OfPtdW7OxmqtFrzouO+vI0dsGREVYGc8oBSxkzUiRaPoS0sM+AB7nj/+FDlj1HD9RzBQ1soYygia4hvaXL1p0edMv26tW5w71h27MNQpPl3ig/T6qUAryomXIEqqgy9DwROcf5CVpqOTTXAhz+Jvf0CclrR5W/imjM2Yw3/lHdOQI+cLJH/VYPS2emQRrTkqfzgZ2JGH3mXSaItHjdLAzEHMTm0YsjM1UDPZTZEdx5fyOx2TVjA97MKfYqpSJBbH2XcSd3x3W5plmE="
  app: abcontrol-spring-boot-microser